baseURL = "https://rjai.me"
languageCode = "en-us"
title = "rjai.me - A personal blog about scientific software, music and miscellanea"
theme = "paper"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
disableKinds = ["taxonomy","taxonomyTerm"]

[params]
author = "Jaime RGP"
shortTitle = "rjai.me"
description = "A personal blog about scientific software, music and miscellanea"

    [[params.footer]]
        identifier = "github"
        name = "GitHub"
        pre = "<i class='fab fa-github'></i>"
        url = "https://github.com/jaimergp"
        weight = 10

    [[params.footer]]
        identifier = "bluesky"
        name = "BlueSky"
        pre = "<i class='fab fa-bluesky'></i>"
        url = "https://bsky.app/profile/rjai.me"
        weight = 20
